# Generated by Django 2.1 on 2018-03-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover_img', models.CharField(max_length=200)),
                ('category_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('click_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('praise_count', models.IntegerField()),
                ('sort', models.SmallIntegerField()),
                ('is_show', models.BooleanField()),
                ('is_hot', models.BooleanField()),
                ('is_top', models.BooleanField()),
                ('is_essence', models.BooleanField()),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.IntegerField()),
            ],
        ),
    ]
