# Generated by Django 2.0.3 on 2018-03-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('cover_img', models.ImageField(default='', max_length=200, null=True, upload_to='', verbose_name='图片封面')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='点击数')),
                ('user_id', models.PositiveIntegerField(default=0, verbose_name='点击数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='点击数')),
                ('praise_count', models.PositiveIntegerField(default=0, verbose_name='点击数')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='点击数')),
                ('is_show', models.BooleanField(default=1, verbose_name='是否显示')),
                ('is_hot', models.BooleanField(default=0, verbose_name='是否热门')),
                ('is_top', models.BooleanField(default=0, verbose_name='是否置顶')),
                ('is_essence', models.BooleanField(default=0, verbose_name='是否精华')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256, verbose_name='用户名')),
                ('other_name', models.CharField(default='', max_length=256, verbose_name='昵称')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='邮件')),
                ('avatar', models.CharField(default='', max_length=100, verbose_name='头像')),
                ('password', models.CharField(default='', max_length=100, verbose_name='密码')),
                ('salt', models.CharField(default='', max_length=100, verbose_name='掩码')),
                ('qq', models.CharField(default=0, max_length=100, verbose_name='QQ')),
                ('mobile_phone', models.CharField(default=0, max_length=100, verbose_name='手机')),
                ('cps_type', models.CharField(default=0, max_length=100, verbose_name='用户类型')),
                ('sex', models.CharField(default=0, max_length=100, verbose_name='性别')),
                ('birthday', models.DateField(default=0, max_length=100, verbose_name='生日')),
                ('exp_value', models.CharField(default=0, max_length=100, verbose_name='经验')),
                ('description', models.TextField(default='', max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
