# Generated by Django 2.0.3 on 2018-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_adposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_img',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_essence',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='is_hot',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='is_show',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='praise_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150, verbose_name='标题'),
        ),
    ]
