# Generated by Django 2.0.3 on 2018-03-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180328_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.CharField(default='', max_length=100, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.CharField(default=0, max_length=100, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='member',
            name='cps_type',
            field=models.CharField(default=0, max_length=100, verbose_name='用户类型'),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='邮件'),
        ),
        migrations.AddField(
            model_name='member',
            name='exp_value',
            field=models.CharField(default=0, max_length=100, verbose_name='经验'),
        ),
        migrations.AddField(
            model_name='member',
            name='mobile_phone',
            field=models.CharField(default=0, max_length=100, verbose_name='手机'),
        ),
        migrations.AddField(
            model_name='member',
            name='other_name',
            field=models.CharField(default='', max_length=256, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='member',
            name='qq',
            field=models.CharField(default=0, max_length=100, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='member',
            name='salt',
            field=models.CharField(default='', max_length=100, verbose_name='掩码'),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(default=0, max_length=100, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.CharField(max_length=256, verbose_name='用户名'),
        ),
    ]
